language: python

sudo: false

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.4
    env: TEST_TARGET=default
  - python: 3.5
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=coding_standards
  allow_failures:
  - python: 3.6
    env: TEST_TARGET=coding_standards

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update conda --yes
    - conda config --add channels conda-forge --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file test_requirements.txt
    - source activate TEST

# Test source distribution.
install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install compliance-checker-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == "default" ]]; then
      py.test -s -rxs -v ;
    fi

  - if [[ $TEST_TARGET == "coding_standards" ]]; then
      flake8 --ignore=E501,E251,E221,E201,E202,E203 -qq --statistics . ;
    fi
